---
# K3s shared variables
cp_group: "controlplane_{{ env }}"
worker_group: "worker_{{ env }}"
k3s_etcd_datastore: true
# Do not deploy the following
k3s_no_traefik: true
k3s_no_servicelb: true
k3s_no_metrics_server: true
k3s_no_flannel: true
# k3s_no_local_storage: true
k3s_flannel_backend: "none"
k3s_become_for_all: true
# Use experimental features (spooky!)
k3s_use_experimental: false

# Enable debugging
k3s_debug: true
